tech: Add gradle & simplify
chutney-testing/chutney-project-template pull request #3
Opened 2023-01-12 17:58 UTC by bessonm

2023-01-13 15:10 UTC, nbrouand requested changes

2023-01-13 15:10 UTC, nbrouand commented on src/test/kotlin/com/chutneytesting/hello/RunHelloMultipleEnvironmentTests.kt
> -import com.chutneytesting.kotlin.launcher.Launcher
Used in Readme, you should update it with your new examples

2023-01-13 15:18 UTC, boddissattva commented on pom.xml
> +                    <version>3.0.0-M7</version>
In property like surefire. It seems that those two plugins from Surefire follow the same versionning cycle. Maybe one property coud be enough. Version M8 exists.

2023-01-16 14:50 UTC, nbrouand approved these changes

2023-01-16 14:51 UTC, merged